### ISSUE TITLE
Beta Problems

### ISSUE THREAD

**Issue by Kauziin** [Osaxely/mc_addons_manager#24]
• Add-ons give access to Xbox storage denied
• Installing add-ons will cause your Minecraft to malfunction causing performance issues.
• The "options" tab does not appear

- Strong points -

• Import is much faster
• Many bugs have been fixed by importing add-ons
• The app appears to be running faster

- My problem -

• My Minecraft won't open anymore

**Comment by Osaxely** [comment]
Hello, the problem will be fixed in some hours (if certification is fast) :) After that, you'll probably have to remove EVERY packs that you have imported with 1.5.2, but you can import them again with this version.
Since you're in beta, you will have to wait only some minutes ! (Will be precised on Twitter account)
