### ISSUE TITLE
[BUG] Packs doesn't import

### ISSUE THREAD

**Issue by Razzyrach2** [Osaxely/mc_addons_manager#45]
It won't let me import any packs, whenever I press import on one it says installing pack then nothing comes up.
I'm trying to install the SEUS PE shader.

**Comment by Osaxely** [comment]
Hello, if I understand correctly, your pack doesn't show up in MC Addons Manager after importing ?

**Comment by Razzyrach2** [comment]
That's correct

**Comment by Osaxely** [comment]
Ok ! If there aren't showing in Minecraft too, it's probably because it was not imported.
Normally the pack is imported when the app has told you 'Do you want to delete the source file ?'. In any case, I will test your pack during the day to see what causes the problem.

**Comment by Razzyrach2** [comment]
Alright thank you!

**Comment by Chronicoverride** [comment]
Sorry for the late response @Razzyrach2. Most shaders don't work on Bedrock Edition. Since Minecraft updated the game and replaced the engine with Render Dragon all of the old shaders no longer work. There is nothing we can do about that. The shader creators have to make new shaders that run on the new engine render dragon.  We have a list of recommended mods and working shaders in the discord server (Currently there are only 2 and they arent very good ones yet). Feel free to join the server to access the list: https://discord.gg/Xqdwvkz
