### ISSUE TITLE
[BUG] the Import/Export Wont Stop loading

### ISSUE THREAD

**Issue by MaxOmniSayian** [Osaxely/mc_addons_manager#52]
**Describe the bug**
When ever i click import or Export It Brings up a never Ending Loading Screen

**Expected behavior**
Me To be able to click import or export and. Install mods with no difficulty

**Screenshots (Optional)**
![20210309_190518_HDR](https://user-images.githubusercontent.com/80368862/110560353-75729900-810b-11eb-8fff-487e08bff9c2.jpg)

.

**Comment by MaxOmniSayian** [comment]
@Osaxely

**Comment by Osaxely** [comment]
Hello, this bug will be fixed in the next update !
This update is in developement since a bunch of months, but the release is very soon :)

**Comment by MaxOmniSayian** [comment]
Thank you😁

**Comment by Chronicoverride** [comment]
![PromoImage160_en](https://user-images.githubusercontent.com/65269683/112144479-a93fcb00-8baf-11eb-8405-a64315544a98.png)
Update this Friday!

**Comment by Chronicoverride** [comment]
The new update is now available for download. It addresses all known issues. Please update your app and give it another shot.

**Comment by maffu202** [comment]
has the export feature been put back in to the newest release ?

**Comment by Osaxely** [comment]
Not actually because Xbox one filesystem is very limited, but I will try to impletement that in the other update. Sorry for the inconvenience :(
Else if it doesn't bother you, I can add it again, but the application will not be able to pack into zip (It will be a folder)

**Comment by maffu202** [comment]
I don’t mind it being a folder as I have to unzip it to edit files inside saves anyway!  I would love the export system back if possible or if you want just sent me a older version I can put on my xbox to get the function back thanks for your speedy reply   Sent from Mail for Windows 10 From: OsaxelySent: 17 April 2021 11:47To: Osaxely/mc_addons_managerCc: maffu202; CommentSubject: Re: [Osaxely/mc_addons_manager] [BUG] the Import/Export Wont Stop loading (#52) Not actually because Xbox one filesystem is very limited, but I will try to impletement that in the other update. Sorry for the inconvenience :(Else if it doesn't bother you, I can add it again, but the application will not be able to pack into zip (It will be a folder)—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Osaxely** [comment]
Okay, I will add this function back in the next hotfix :) Even if it will be only folder for now. And yes, it's very weird that it's that limited. Xbox allows to make folder, but not to compress into zip.

**Comment by maffu202** [comment]
Thanks so much . Sent from Mail for Windows 10 From: OsaxelySent: 17 April 2021 13:22To: Osaxely/mc_addons_managerCc: maffu202; CommentSubject: Re: [Osaxely/mc_addons_manager] [BUG] the Import/Export Wont Stop loading (#52) Okay, I will add this function back in the next hotfix :) Even if it will be only folder for now. And yes, it's very weird that it's that limited. Xbox allows to make folder, but not to compress into zip.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by maffu202** [comment]
Was the export function added back in? I see there was an update yesterday just wondering if you have had time to change that back ?  Sent from Mail for Windows 10 From: OsaxelySent: 17 April 2021 13:22To: Osaxely/mc_addons_managerCc: maffu202; CommentSubject: Re: [Osaxely/mc_addons_manager] [BUG] the Import/Export Wont Stop loading (#52) Okay, I will add this function back in the next hotfix :) Even if it will be only folder for now. And yes, it's very weird that it's that limited. Xbox allows to make folder, but not to compress into zip.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Osaxely** [comment]
Hello, no it wasn't added actually, but don't worry, it will be here again in a few time :)
